// GENERATED by review/accuracy/v7/make-gust-table.mjs from review/accuracy/v7/results-score7.json — do not edit.
// Placeholder until the v7 results exist: nothing ships, every place keeps today's gust rule (55 km/h, no correction).
export const GUST_TABLE = {
  "id": "v7-2026-09-28",
  "regions": {},
  "strandZone": null,
  "stations": []
};
