// GENERATED by review/accuracy/v7/make-gust-table.mjs from review/accuracy/v7/results-score7.json — do not edit.
// Gust rules per region and gust corrections per SA Weather Service station (PLAN review/accuracy/v7/PLAN.md, EVAL §14).
// regions: the Windy rung's gust line (km/h) and "enough sources at 25 km/h" count, where that region's test passed.
// stations: each gust × sectors[N, NE, E, SE, S, SW, W, NW] (Open-Meteo's bearing) at the towns listed (within the town's km, default 5).
export const GUST_TABLE = {
  "id": "v7-2026-09-28",
  "regions": {
    "Eastern Cape": {
      "rule": "R1",
      "gustLineKph": 50,
      "sourcesAt25": 0
    },
    "Free State": {
      "rule": "R1",
      "gustLineKph": 45,
      "sourcesAt25": 0
    },
    "KZN coast": {
      "rule": "R1",
      "gustLineKph": 50,
      "sourcesAt25": 0
    },
    "KZN inland": {
      "rule": "R1",
      "gustLineKph": 50,
      "sourcesAt25": 0
    },
    "Northern Cape": {
      "rule": "R1",
      "gustLineKph": 50,
      "sourcesAt25": 0
    },
    "West Coast": {
      "rule": "R3",
      "gustLineKph": 55,
      "sourcesAt25": 2
    }
  },
  "strandZone": {
    "rule": "R3",
    "gustLineKph": 55,
    "sourcesAt25": 2
  },
  "stations": [
    {
      "id": "68176",
      "name": "MARA",
      "lat": -23.15,
      "lon": 29.567,
      "sectors": [
        0.8,
        0.8,
        0.8,
        0.8,
        0.8,
        0.8,
        0.8,
        0.8
      ],
      "headline": true,
      "towns": [
        {
          "name": "Mara",
          "lat": -23.11667,
          "lon": 29.63333,
          "km": 4
        }
      ]
    },
    {
      "id": "68817",
      "name": "CAPE TOWN - PORTNET",
      "lat": -33.9,
      "lon": 18.433,
      "sectors": [
        0.846,
        0.846,
        0.846,
        1.105,
        0.868,
        0.846,
        0.846,
        0.846
      ],
      "headline": true,
      "towns": [
        {
          "name": "Cape Town (city centre)",
          "lat": -33.92584,
          "lon": 18.42322,
          "km": 1.2
        },
        {
          "name": "Foreshore",
          "lat": -33.92278,
          "lon": 18.4409,
          "km": 1.5
        },
        {
          "name": "Roggebaai",
          "lat": -33.91667,
          "lon": 18.43333,
          "km": 1
        },
        {
          "name": "De Waterkant",
          "lat": -33.91528,
          "lon": 18.41667,
          "km": 1
        },
        {
          "name": "Green Point",
          "lat": -33.90504,
          "lon": 18.40725,
          "km": 1.5
        },
        {
          "name": "Mouille Point",
          "lat": -33.90027,
          "lon": 18.40531,
          "km": 1
        },
        {
          "name": "Woodstock",
          "lat": -33.93156,
          "lon": 18.4448,
          "km": 1.5
        },
        {
          "name": "Salt River",
          "lat": -33.93339,
          "lon": 18.4572,
          "km": 1.5
        },
        {
          "name": "Paarden Eiland",
          "lat": -33.9163,
          "lon": 18.47265,
          "km": 1.5
        }
      ]
    }
  ]
};
