// GENERATED by review/accuracy/v2/make-table.mjs — do not edit by hand; re-run it (and --check guards drift).
// The corrected five-model consensus for today's (days[0], latest-run lead) and tomorrow's (days[1], 24-h lead)
// high and low: per model, a seasonal bias (°C, model minus airport) and a weight (sums to 1). Learned at
// 16 SA airports (FACT FALW FAGG FAPE FAEL FAUT FALE FAOR FAWB FABL FAUP FAKM FAMM FAKN FAHS FAPP), 2025-01-01 → 2026-09-24.
// Blocked where the backtest found it made things worse: Lowveld (precision.js).
export const PRECISION_TABLE = {
  "id": "v2-2025-01-01-2026-09-24",
  "alpha": 0.5,
  "models": [
    "best_match",
    "gfs_seamless",
    "icon_seamless",
    "ukmo_seamless",
    "meteofrance_seamless"
  ],
  "trainedOn": "2025-01-01..2026-09-24",
  "stations": [
    "FACT",
    "FALW",
    "FAGG",
    "FAPE",
    "FAEL",
    "FAUT",
    "FALE",
    "FAOR",
    "FAWB",
    "FABL",
    "FAUP",
    "FAKM",
    "FAMM",
    "FAKN",
    "FAHS",
    "FAPP"
  ],
  "blocked": [
    "Lowveld"
  ],
  "days": [
    {
      "max": {
        "bias": {
          "best_match": {
            "DJF": -0.446,
            "MAM": -0.727,
            "JJA": -0.789,
            "SON": -0.289
          },
          "gfs_seamless": {
            "DJF": 0.28,
            "MAM": 0.224,
            "JJA": -0.484,
            "SON": 0.456
          },
          "icon_seamless": {
            "DJF": -0.557,
            "MAM": -0.452,
            "JJA": -0.438,
            "SON": -0.536
          },
          "ukmo_seamless": {
            "DJF": 0.296,
            "MAM": -0.244,
            "JJA": -0.654,
            "SON": 0.222
          },
          "meteofrance_seamless": {
            "DJF": 0.115,
            "MAM": -0.308,
            "JJA": -0.583,
            "SON": 0.319
          }
        },
        "w": {
          "best_match": 0.235,
          "gfs_seamless": 0.168,
          "icon_seamless": 0.18,
          "ukmo_seamless": 0.189,
          "meteofrance_seamless": 0.228
        }
      },
      "min": {
        "bias": {
          "best_match": {
            "DJF": 0.097,
            "MAM": 0.464,
            "JJA": 1.093,
            "SON": 0.417
          },
          "gfs_seamless": {
            "DJF": 0.527,
            "MAM": 1.717,
            "JJA": 2.835,
            "SON": 1.453
          },
          "icon_seamless": {
            "DJF": 0.391,
            "MAM": 0.517,
            "JJA": 0.69,
            "SON": 0.636
          },
          "ukmo_seamless": {
            "DJF": -0.267,
            "MAM": 0.031,
            "JJA": -0.038,
            "SON": -0.12
          },
          "meteofrance_seamless": {
            "DJF": 1.468,
            "MAM": 1.274,
            "JJA": 1.603,
            "SON": 1.679
          }
        },
        "w": {
          "best_match": 0.232,
          "gfs_seamless": 0.135,
          "icon_seamless": 0.191,
          "ukmo_seamless": 0.212,
          "meteofrance_seamless": 0.231
        }
      }
    },
    {
      "max": {
        "bias": {
          "best_match": {
            "DJF": -0.33,
            "MAM": -0.679,
            "JJA": -0.933,
            "SON": -0.265
          },
          "gfs_seamless": {
            "DJF": 0.56,
            "MAM": 0.336,
            "JJA": -0.397,
            "SON": 0.648
          },
          "icon_seamless": {
            "DJF": -0.618,
            "MAM": -0.671,
            "JJA": -0.681,
            "SON": -0.576
          },
          "ukmo_seamless": {
            "DJF": 0.09,
            "MAM": -0.569,
            "JJA": -1.174,
            "SON": 0.167
          },
          "meteofrance_seamless": {
            "DJF": 0.12,
            "MAM": -0.384,
            "JJA": -0.696,
            "SON": 0.532
          }
        },
        "w": {
          "best_match": 0.235,
          "gfs_seamless": 0.197,
          "icon_seamless": 0.191,
          "ukmo_seamless": 0.162,
          "meteofrance_seamless": 0.214
        }
      },
      "min": {
        "bias": {
          "best_match": {
            "DJF": 0.27,
            "MAM": 0.464,
            "JJA": 0.919,
            "SON": 0.571
          },
          "gfs_seamless": {
            "DJF": 0.543,
            "MAM": 1.803,
            "JJA": 2.926,
            "SON": 1.527
          },
          "icon_seamless": {
            "DJF": 0.351,
            "MAM": 0.505,
            "JJA": 0.619,
            "SON": 0.684
          },
          "ukmo_seamless": {
            "DJF": -0.083,
            "MAM": 0.136,
            "JJA": -0.001,
            "SON": 0.024
          },
          "meteofrance_seamless": {
            "DJF": 2.034,
            "MAM": 1.676,
            "JJA": 1.943,
            "SON": 2.218
          }
        },
        "w": {
          "best_match": 0.218,
          "gfs_seamless": 0.144,
          "icon_seamless": 0.195,
          "ukmo_seamless": 0.247,
          "meteofrance_seamless": 0.196
        }
      }
    }
  ]
};
