// GENERATED by review/accuracy/v6/make-wind-weights.mjs — do not edit by hand; re-run it (and --check guards drift).
// Wind's own say-per-source (review/accuracy/v6/PLAN.md, EVAL §13): in the regions below the now-wind is each real
// source's own wind weighted by how right it was at the region's airport (1 / squared error, clamped 0.05–0.50, on the
// first half of the recorder's readings 25–28 Sept 2026) × k, proven on the second half. Everywhere else: the v5 rule
// (wind-table.js). Order: Open-Meteo, WeatherAPI, Pirate Weather, MET Norway, Tomorrow.io.
// Regions: Eastern Cape. Hourly winds follow: yes (OM, WA, MET, TI renormalised × k4).
export const WIND_WEIGHTS = {
  "id": "v6-live-2026-09-28",
  "sources": [
    "Open-Meteo",
    "WeatherAPI",
    "Pirate Weather",
    "MET Norway",
    "Tomorrow.io"
  ],
  "window": {
    "from": "2026-09-25T16:10:06.605Z",
    "to": "2026-09-28T11:10:01.850Z"
  },
  "hourlyFollows": true,
  "regions": {
    "Eastern Cape": {
      "airport": "FAPE",
      "weights": [
        0.1728,
        0.1496,
        0.3835,
        0.1617,
        0.1325
      ],
      "k": 1.0542,
      "k4": 1.1168
    }
  }
};
