// GENERATED by review/accuracy/v5/make-wind-table.mjs — do not edit by hand; re-run it (and --check guards drift).
// The now-wind and the hourly winds: today's weighted blend × a ratio per region × season × day-part
// (learned at 16 SA airports on 2025, the three source guesses averaged, clamped to [0.7, 1.6]; proven on 2026 — EVAL §12).
// Blocked (today's blend): no region; within 15 km of Strand's station 68911 (the rule read too high there).
// The hero's Windy line on the corrected number: 27.5 km/h.
export const WIND_TABLE = {
  "id": "v5-2025-three-guesses",
  "rule": "BC",
  "learnedOn": "2025-01-01..2025-12-31",
  "provenOn": "2026-01-01..2026-09-24",
  "regions": [
    "Western Cape",
    "West Coast",
    "Garden Route",
    "Eastern Cape",
    "KZN coast",
    "Highveld",
    "Free State",
    "Northern Cape",
    "North West",
    "Lowveld",
    "Limpopo"
  ],
  "blockedRegions": [],
  "strandBlocked": true,
  "headline": {
    "ships": true,
    "thresholdKph": 27.5
  },
  "ratios": {
    "Western Cape": {
      "DJF": {
        "night": 1.6,
        "morning": 1.6,
        "afternoon": 1.6,
        "evening": 1.6
      },
      "MAM": {
        "night": 1.6,
        "morning": 1.6,
        "afternoon": 1.6,
        "evening": 1.6
      },
      "JJA": {
        "night": 1.6,
        "morning": 1.6,
        "afternoon": 1.6,
        "evening": 1.6
      },
      "SON": {
        "night": 1.6,
        "morning": 1.6,
        "afternoon": 1.6,
        "evening": 1.6
      }
    },
    "West Coast": {
      "DJF": {
        "night": 0.79,
        "morning": 1.029,
        "afternoon": 1.091,
        "evening": 0.964
      },
      "MAM": {
        "night": 0.744,
        "morning": 0.804,
        "afternoon": 1.119,
        "evening": 0.855
      },
      "JJA": {
        "night": 0.7,
        "morning": 0.763,
        "afternoon": 1.005,
        "evening": 0.731
      },
      "SON": {
        "night": 0.713,
        "morning": 0.873,
        "afternoon": 1.094,
        "evening": 0.837
      }
    },
    "Garden Route": {
      "DJF": {
        "night": 1.087,
        "morning": 1.154,
        "afternoon": 1.139,
        "evening": 1.092
      },
      "MAM": {
        "night": 1.265,
        "morning": 1.237,
        "afternoon": 1.304,
        "evening": 1.361
      },
      "JJA": {
        "night": 1.12,
        "morning": 1.184,
        "afternoon": 1.249,
        "evening": 1.188
      },
      "SON": {
        "night": 1.13,
        "morning": 1.244,
        "afternoon": 1.242,
        "evening": 1.161
      }
    },
    "Eastern Cape": {
      "DJF": {
        "night": 1.231,
        "morning": 1.272,
        "afternoon": 1.314,
        "evening": 1.266
      },
      "MAM": {
        "night": 1.051,
        "morning": 1.167,
        "afternoon": 1.287,
        "evening": 1.167
      },
      "JJA": {
        "night": 0.956,
        "morning": 1.104,
        "afternoon": 1.3,
        "evening": 1.115
      },
      "SON": {
        "night": 1.144,
        "morning": 1.238,
        "afternoon": 1.328,
        "evening": 1.213
      }
    },
    "KZN coast": {
      "DJF": {
        "night": 0.923,
        "morning": 0.99,
        "afternoon": 1.004,
        "evening": 0.977
      },
      "MAM": {
        "night": 0.759,
        "morning": 0.944,
        "afternoon": 1.028,
        "evening": 0.846
      },
      "JJA": {
        "night": 0.738,
        "morning": 0.928,
        "afternoon": 1.049,
        "evening": 0.854
      },
      "SON": {
        "night": 0.867,
        "morning": 1.041,
        "afternoon": 0.989,
        "evening": 0.929
      }
    },
    "Highveld": {
      "DJF": {
        "night": 1.404,
        "morning": 1.495,
        "afternoon": 1.517,
        "evening": 1.519
      },
      "MAM": {
        "night": 1.266,
        "morning": 1.427,
        "afternoon": 1.546,
        "evening": 1.387
      },
      "JJA": {
        "night": 1.297,
        "morning": 1.494,
        "afternoon": 1.409,
        "evening": 1.276
      },
      "SON": {
        "night": 1.328,
        "morning": 1.427,
        "afternoon": 1.401,
        "evening": 1.43
      }
    },
    "Free State": {
      "DJF": {
        "night": 0.951,
        "morning": 1.187,
        "afternoon": 1.254,
        "evening": 1.072
      },
      "MAM": {
        "night": 0.7,
        "morning": 0.891,
        "afternoon": 1.08,
        "evening": 0.7
      },
      "JJA": {
        "night": 0.7,
        "morning": 0.887,
        "afternoon": 1.189,
        "evening": 0.841
      },
      "SON": {
        "night": 0.905,
        "morning": 1.048,
        "afternoon": 1.143,
        "evening": 1.121
      }
    },
    "Northern Cape": {
      "DJF": {
        "night": 0.925,
        "morning": 1.002,
        "afternoon": 1.022,
        "evening": 1.047
      },
      "MAM": {
        "night": 0.812,
        "morning": 0.911,
        "afternoon": 0.966,
        "evening": 0.953
      },
      "JJA": {
        "night": 0.852,
        "morning": 0.896,
        "afternoon": 0.929,
        "evening": 0.817
      },
      "SON": {
        "night": 0.832,
        "morning": 0.941,
        "afternoon": 0.985,
        "evening": 0.896
      }
    },
    "North West": {
      "DJF": {
        "night": 1.041,
        "morning": 1.114,
        "afternoon": 1.052,
        "evening": 1.136
      },
      "MAM": {
        "night": 1.065,
        "morning": 1.096,
        "afternoon": 1.107,
        "evening": 1.171
      },
      "JJA": {
        "night": 1.075,
        "morning": 1.165,
        "afternoon": 1.072,
        "evening": 1.056
      },
      "SON": {
        "night": 1.174,
        "morning": 1.159,
        "afternoon": 1.047,
        "evening": 1.072
      }
    },
    "Lowveld": {
      "DJF": {
        "night": 0.865,
        "morning": 0.864,
        "afternoon": 1.003,
        "evening": 1.166
      },
      "MAM": {
        "night": 0.785,
        "morning": 0.895,
        "afternoon": 1,
        "evening": 1.06
      },
      "JJA": {
        "night": 0.854,
        "morning": 0.838,
        "afternoon": 0.949,
        "evening": 1.126
      },
      "SON": {
        "night": 1.08,
        "morning": 0.958,
        "afternoon": 1.053,
        "evening": 1.294
      }
    },
    "Limpopo": {
      "DJF": {
        "night": 0.857,
        "morning": 0.932,
        "afternoon": 1.121,
        "evening": 0.928
      },
      "MAM": {
        "night": 0.908,
        "morning": 0.898,
        "afternoon": 1.087,
        "evening": 0.843
      },
      "JJA": {
        "night": 0.986,
        "morning": 0.958,
        "afternoon": 1.108,
        "evening": 0.871
      },
      "SON": {
        "night": 0.921,
        "morning": 1.027,
        "afternoon": 1.196,
        "evening": 0.965
      }
    }
  }
};
