// From the scorer's results to the live map (PLAN §6): which live stations ship which rule (per region, by the bar and
// the S/SC tie-break), and every town's station — or none, with the reason — for the record (towns-stations.json) and
// for production (api/_lib/station-map.js, towns with a station only).
//   node review/accuracy/stations/make-map.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { scoredStations } from './stations.mjs';
import { loadTowns } from './towns.mjs';
import { ensure, coastPoints, linePoints, kmBetween } from './geo.mjs';
import { geoPasses } from './pairs.mjs';
import { regionOf } from '../../../api/_lib/regions.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const TARGET = path.join(here, '../../../api/_lib/station-map.js');
const R = JSON.parse(readFileSync(path.join(here, 'results-score.json'), 'utf8'));
const D = R.D;
const avg = (a) => a.reduce((s, x) => s + x, 0) / a.length;

// ---- per region: S, SC or nothing (PLAN §5: if both pass, SC when its catch is higher and its false rate is no more
// than 0.5 per 100 above S's — both averaged over the three guesses)
const ships = {};
for (const [g, res] of Object.entries(R.regions)) {
  const s = res.S?.pass, sc = res.SC?.pass;
  let rule = null;
  if (s && sc) {
    const c = (k) => avg(res[k].own.per.map((p) => p.R.caught)), f = (k) => avg(res[k].own.per.map((p) => p.R.falsePer100));
    rule = c('SC') > c('S') && f('SC') - f('S') <= 0.5 ? 'SC' : 'S';
  } else if (sc) rule = 'SC'; else if (s) rule = 'S';
  if (rule) ships[g] = rule;
}
const F = R.tune.S.chosen.F, T = R.tune.SC?.chosen?.T ?? null;
const all = scoredStations();
const live = all.filter((s) => s.kind === 'metar' && ships[regionOf(s.lat, s.lon)]);
const towns = loadTowns(all);
const pts = [];
for (const t of towns) for (const s of live) if (kmBetween(t.lat, t.lon, s.lat, s.lon) <= Math.max(D.coast, D.inland)) { pts.push(...coastPoints(t.lat, t.lon), ...linePoints(t.lat, t.lon, s.lat, s.lon)); }
await ensure([...pts, ...live.flatMap((s) => coastPoints(s.lat, s.lon))]);

const record = [];
for (const t of towns) {
  const near = live.map((s) => ({ s, km: kmBetween(t.lat, t.lon, s.lat, s.lon) })).sort((a, b) => a.km - b.km);
  let station = null, reason = 'no live station within 10 km';
  for (const { s, km } of near) {
    const g = geoPasses(t, s);
    const Dmax = g.coastal === undefined ? Math.min(D.coast, D.inland) : g.coastal ? D.coast : D.inland;
    if (km > Math.max(D.coast, D.inland)) break;
    if (!g.ok) { reason = `${s.id}: ${g.why}`; continue; }
    if (km > Dmax) { reason = `${s.id}: beyond ${Dmax} km`; continue; }
    station = s.id; reason = `${s.id} ${km.toFixed(1)} km, ${g.coastal ? 'coastal' : 'inland'}`; break;
  }
  record.push({ name: t.name, lat: t.lat, lon: t.lon, pop: t.pop, code: t.code, region: regionOf(t.lat, t.lon), station, reason });
}
const covered = record.filter((t) => t.station);
const popAll = record.filter((t) => t.pop >= 1000 && t.code !== 'PPLX').reduce((s, t) => s + t.pop, 0);
const popCov = covered.filter((t) => t.pop >= 1000 && t.code !== 'PPLX').reduce((s, t) => s + t.pop, 0);
const summary = { ships, F, T, D, liveStations: live.map((s) => s.id), towns: record.length, townsCovered: covered.length,
  places1000: record.filter((t) => t.pop >= 1000 && t.code !== 'PPLX').length, places1000Covered: covered.filter((t) => t.pop >= 1000 && t.code !== 'PPLX').length,
  peopleInPlaces1000: popAll, peopleCovered: popCov };
writeFileSync(path.join(here, 'towns-stations.json'), `{"summary": ${JSON.stringify(summary)},\n"towns": [\n${record.map((t) => JSON.stringify(t)).join(',\n')}\n]}\n`);

const r4 = (x) => Math.round(x * 1e4) / 1e4;
const table = {
  id: `stations-${R.generatedAt.slice(0, 10)}`,
  D, F, T,
  stations: Object.fromEntries(live.map((s) => [s.id, { name: s.name, lat: s.lat, lon: s.lon, region: regionOf(s.lat, s.lon), rule: ships[regionOf(s.lat, s.lon)] }])),
  towns: covered.map((t) => [t.name, r4(t.lat), r4(t.lon), t.station]),
};
const src = `// GENERATED by review/accuracy/stations/make-map.mjs from review/accuracy/stations/results-score.json — do not edit.
// "Now" follows the live station (PLAN review/accuracy/stations/PLAN.md, EVAL §15): the airports whose region passed
// (rule S: the latest METAR within F hours is pumping → Windy; SC: S, or the station-minus-model gap, fading to nothing
// over T hours, lifts the numbers over the place's lines), and the towns each one represents (within D km, same
// exposure, height within 150 m coastal / 250 m inland, no ridge between). [name, lat, lon, station].
export const STATION_MAP = ${JSON.stringify(table, null, 1)};
`;
if (process.argv.includes('--check')) {
  const cur = readFileSync(TARGET, 'utf8').replace(/\r\n/g, '\n');
  if (cur !== src) { console.error('station-map.js is out of date with the results'); process.exit(1); }
  console.log('station-map.js matches the results');
} else {
  writeFileSync(TARGET, src);
  console.log(JSON.stringify(summary, null, 1));
}
