#!/usr/bin/env bash
# Promote 1,008 staged WebP images into the production asset tree.
#
# Strategy: copy (not move) from ../pw-image-staging/compressed/ so the
# staging tree stays intact on disk as in-place rollback source.
#
# Plan: docs/promote-plan-2026-05-24.md
# Run from repo root.
#
# Round 2 hardening (after codex adversarial review):
#  - .gitattributes: explicit `*.webp binary` rule (no text=auto on binaries)
#  - Per-file -s (non-empty) check, not just -f (exists) — catches OneDrive
#    cloud-only placeholders that exist but are zero-byte
#  - wc -l output stripped of whitespace before integer comparison
#  - Untracked junk preflight: aborts if any unexpected untracked dir/file
#    would risk accidental git add
#  - Programmatic commit-stack verification: asserts exactly 6 unpushed commits
#    and prints their SHAs for operator inspection
#  - Defensive `|| true` on every grep pipeline
#  - 144 per-slot spot checks (one file per cond×week×time) instead of just 5

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

STAGING="../pw-image-staging/compressed"
DEST_BASE="assets/images/bg"

CONDITIONS=(clear cloudy cold cold-clear fog heat rain storm wind)
OLD_CONDITIONS=(clear cloudy cold fog heat rain storm wind)   # have old flat JPGs to remove
WEEKS=(1 2 3 4)
TIMES=(dawn day dusk night)

# Allowed untracked artefacts (session noise, not for commit). Anything outside
# this set in `git status --porcelain '??'` will halt the script.
ALLOWED_UNTRACKED_PATTERNS=(
  ".agents/"
  ".claude/scheduled_tasks.lock"
  ".claude/worktrees/"
  ".playwright-mcp/"
  "AGENTS.md"
  "NATIVE_REVIEW_ST.md"
  "NATIVE_REVIEW_XH.md"
  "NATIVE_REVIEW_ZU.md"
  "eval/"
  # Promote-operation artefacts — included in the promote commit:
  "docs/promote-plan-2026-05-24.md"
  "docs/promote-review-2026-05-24.md"
  "docs/promote-report-2026-05-24.md"
  "docs/promote-commit-message.txt"
  "docs/og-fix-review-2026-05-24.md"
  "scripts/promote-image-library.sh"
  # OG card files regenerated by build-og-images.mjs (new cold-clear.jpg
  # is the only one that's untracked; the others are tracked & modified).
  "og/cold-clear.jpg"
)

log() { printf '\033[36m[promote] %s\033[0m\n' "$*" >&2; }
err() { printf '\033[31m[promote ERROR] %s\033[0m\n' "$*" >&2; exit 1; }

# Strip whitespace from a number (Git Bash's wc -l can emit leading spaces).
num() { printf '%s' "$1" | tr -d '[:space:]'; }

#------------------------------------------------------------
# Phase 1 — pre-flight assertions
#------------------------------------------------------------

log "Phase 1: pre-flight checks"

# 1.1 Staging exists, is a directory, has all 9 buckets
[[ -d "$STAGING" ]] || err "Staging missing: $STAGING"
for c in "${CONDITIONS[@]}"; do
  [[ -d "$STAGING/$c" ]] || err "Staging bucket missing: $STAGING/$c"
done

# 1.2 Staging count is exactly 1008 (4×4×7×9)
STAGING_COUNT=$(num "$(find "$STAGING" -name '*.webp' -type f | wc -l)")
[[ "$STAGING_COUNT" -eq 1008 ]] || err "Staging WebP count is $STAGING_COUNT (expected 1008)"
log "  staging integrity: 1008 WebPs ✓"

# 1.3 Every bucket has exactly 112 files
for c in "${CONDITIONS[@]}"; do
  n=$(num "$(find "$STAGING/$c" -name '*.webp' -type f | wc -l)")
  [[ "$n" -eq 112 ]] || err "Bucket $c has $n WebPs (expected 112)"
done
log "  per-bucket integrity: 9 × 112 ✓"

# 1.4 Every slot has exactly 7 named files AND each is non-empty (OneDrive
#     placeholder check — `-s` rejects zero-byte cloud-only stubs).
for c in "${CONDITIONS[@]}"; do
  for w in "${WEEKS[@]}"; do
    for t in "${TIMES[@]}"; do
      slot="$STAGING/$c/week_$w/$t"
      [[ -d "$slot" ]] || err "Missing slot dir: $slot"
      n=$(num "$(find "$slot" -maxdepth 1 -name '*.webp' -type f | wc -l)")
      [[ "$n" -eq 7 ]] || err "Slot $slot has $n files (expected 7)"
      for i in 1 2 3 4 5 6 7; do
        # -s checks file exists AND is non-empty. A OneDrive placeholder shows
        # up via -f but fails -s. This is the primary OneDrive-race mitigation.
        [[ -s "$slot/$i.webp" ]] || err "File missing or zero-byte (OneDrive placeholder?): $slot/$i.webp"
      done
    done
  done
done
log "  per-slot integrity: 144 × 7 non-empty named 1.webp..7.webp ✓"

# 1.5 default.jpg fallback intact
[[ -s "$DEST_BASE/default.jpg" ]] || err "default.jpg fallback missing or zero-byte at $DEST_BASE/default.jpg"
log "  default.jpg present and non-empty ✓"

# 1.6 No staged changes
STAGED_CHANGES=$(num "$(git diff --cached --name-only | wc -l)")
[[ "$STAGED_CHANGES" -eq 0 ]] || err "Aborting: $STAGED_CHANGES files already staged; reset them first"

# 1.7 Unstaged check — only known intentional modifications allowed:
#   - assets/images/bg/wind/day_6.jpg : pre-existing deletion from prior session
#   - .gitattributes : binary asset rules (round-1 review fix)
#   - api/og.js : OG WebP→JPEG fix (Phase 0 of Option B)
#   - assets/weather-visuals.js : new getOgStaticBackground* helpers
#   - tests/og-paths.test.js : new tests for the static-OG helpers
ALLOWED_UNSTAGED=(
  "assets/images/bg/wind/day_6.jpg"
  ".gitattributes"
  "api/og.js"
  "assets/weather-visuals.js"
  "tests/og-paths.test.js"
)
UNSTAGED=$(git status --porcelain | awk '/^ [DM]/{print $2}' || true)
UNEXPECTED_UNSTAGED=""
while IFS= read -r path; do
  [[ -z "$path" ]] && continue
  matched=0
  for allowed in "${ALLOWED_UNSTAGED[@]}"; do
    if [[ "$path" == "$allowed" ]]; then matched=1; break; fi
  done
  if [[ "$matched" -eq 0 ]]; then
    UNEXPECTED_UNSTAGED+="$path"$'\n'
  fi
done <<< "$UNSTAGED"
if [[ -n "$UNEXPECTED_UNSTAGED" ]]; then
  err "Aborting: unexpected unstaged changes:
$UNEXPECTED_UNSTAGED"
fi
log "  unstaged check: only known intentional modifications (5 allowlisted paths) ✓"

# 1.8 Untracked check — must match the allowlist (anything else halts so
#     the operator can't accidentally `git add .` junk into the promote commit)
UNTRACKED=$(git status --porcelain | awk '/^\?\?/{print $2}' || true)
UNEXPECTED_UNTRACKED=""
while IFS= read -r path; do
  [[ -z "$path" ]] && continue
  matched=0
  for pattern in "${ALLOWED_UNTRACKED_PATTERNS[@]}"; do
    if [[ "$path" == "$pattern" || "$path" == "$pattern"* ]]; then
      matched=1; break
    fi
  done
  if [[ "$matched" -eq 0 ]]; then
    UNEXPECTED_UNTRACKED+="$path"$'\n'
  fi
done <<< "$UNTRACKED"
if [[ -n "$UNEXPECTED_UNTRACKED" ]]; then
  err "Aborting: unexpected untracked items (not in allowlist):
$UNEXPECTED_UNTRACKED
Either add to ALLOWED_UNTRACKED_PATTERNS, .gitignore, or delete before promote."
fi
log "  untracked check: all known session noise, no surprise files ✓"

# 1.9 Unpushed commit stack — exactly 6 expected
UNPUSHED_COUNT=$(num "$(git log --oneline origin/main..HEAD | wc -l)")
[[ "$UNPUSHED_COUNT" -eq 6 ]] || err "Expected 6 unpushed commits, got $UNPUSHED_COUNT. Stack may be stale."
log "  unpushed commit stack: 6 commits ✓"
log "  --- unpushed stack ---"
git log --oneline origin/main..HEAD | sed 's/^/    /' >&2
log "  --- end stack ---"

# 1.10 HEAD SHA report
HEAD_SHA=$(git rev-parse HEAD)
ORIGIN_SHA=$(git rev-parse origin/main)
log "  HEAD:        $HEAD_SHA"
log "  origin/main: $ORIGIN_SHA"

# 1.11 Vitest baseline
log "  running baseline vitest..."
if ! TEST_OUT=$(npx vitest run 2>&1); then
  err "Baseline vitest FAILED — fix tests before promoting. Last lines:
$(echo "$TEST_OUT" | tail -10)"
fi
BASELINE_PASS=$(num "$(echo "$TEST_OUT" | grep -oE "Tests +[0-9]+ passed" | grep -oE "[0-9]+" | head -1 || true)")
[[ -n "$BASELINE_PASS" && "$BASELINE_PASS" -ge 4485 ]] || err "Baseline pass count '$BASELINE_PASS' < 4485 (regression or parse failure)"
log "  baseline: $BASELINE_PASS tests pass ✓"

#------------------------------------------------------------
# Phase 2 — copy
#------------------------------------------------------------

log "Phase 2: copy WebP files into $DEST_BASE/<cond>/week_*/<time>/"

for c in "${CONDITIONS[@]}"; do
  log "  copying $c..."
  for w in "${WEEKS[@]}"; do
    for t in "${TIMES[@]}"; do
      mkdir -p "$DEST_BASE/$c/week_$w/$t"
      for i in 1 2 3 4 5 6 7; do
        src="$STAGING/$c/week_$w/$t/$i.webp"
        dst="$DEST_BASE/$c/week_$w/$t/$i.webp"
        cp -f -- "$src" "$dst"
        # Per-file post-copy non-empty assertion (OneDrive race guard).
        [[ -s "$dst" ]] || err "Copy produced zero-byte file: $dst (OneDrive sync mid-copy?)"
      done
    done
  done
  n=$(num "$(find "$DEST_BASE/$c" -name '*.webp' -type f | wc -l)")
  [[ "$n" -eq 112 ]] || err "After copy, $c has $n WebPs (expected 112)"
done
log "  copy complete; 1008 non-empty WebPs in place ✓"

#------------------------------------------------------------
# Phase 3 — delete old flat JPGs (per OLD condition, max-depth 1)
#------------------------------------------------------------

log "Phase 3: remove pre-rotation flat JPG files"

REMOVED_TOTAL=0
for c in "${OLD_CONDITIONS[@]}"; do
  # find -delete is atomic per file; collect prints to count.
  removed=$(num "$(find "$DEST_BASE/$c" -maxdepth 1 -type f -name '*.jpg' -print -delete | wc -l)")
  REMOVED_TOTAL=$((REMOVED_TOTAL + removed))
done
log "  removed $REMOVED_TOTAL old JPGs (from 8 condition folders, max-depth 1)"

# Sanity: cold-clear has no old JPGs to remove
[[ -d "$DEST_BASE/cold-clear" ]] || err "cold-clear/ folder unexpectedly missing"
OLD_CC_JPGS=$(num "$(find "$DEST_BASE/cold-clear" -maxdepth 1 -type f -name '*.jpg' | wc -l)")
[[ "$OLD_CC_JPGS" -eq 0 ]] || err "cold-clear/ has unexpected old JPGs: $OLD_CC_JPGS"

#------------------------------------------------------------
# Phase 4 — post-promote invariants
#------------------------------------------------------------

log "Phase 4: post-promote invariants"

# 4.1 1,008 WebPs in production tree
PROD_WEBP=$(num "$(find "$DEST_BASE" -name '*.webp' -type f | wc -l)")
[[ "$PROD_WEBP" -eq 1008 ]] || err "Production WebP count $PROD_WEBP != 1008"
log "  1008 WebPs in production tree ✓"

# 4.2 default.jpg still present at root, non-empty
[[ -s "$DEST_BASE/default.jpg" ]] || err "default.jpg MISSING OR ZERO — emergency restore needed!"
log "  default.jpg preserved ✓"

# 4.3 Zero old JPGs remaining (except default.jpg)
OLD_JPG_REMAINING=$(num "$(find "$DEST_BASE" -name '*.jpg' -type f ! -path "$DEST_BASE/default.jpg" | wc -l)")
[[ "$OLD_JPG_REMAINING" -eq 0 ]] || err "$OLD_JPG_REMAINING old JPG file(s) still present after delete pass"
log "  zero old JPGs remaining (default.jpg root file untouched) ✓"

# 4.4 Per-bucket × per-slot × 7-file invariant
for c in "${CONDITIONS[@]}"; do
  for w in "${WEEKS[@]}"; do
    for t in "${TIMES[@]}"; do
      n=$(num "$(find "$DEST_BASE/$c/week_$w/$t" -maxdepth 1 -name '*.webp' -type f | wc -l)")
      [[ "$n" -eq 7 ]] || err "Slot $c/week_$w/$t has $n WebPs (expected 7)"
    done
  done
done
log "  144 slots × 7 = 1008 invariant ✓"

# 4.5 Exhaustive per-slot spot check — one file per (cond × week × time) = 144
#     real-file existence-and-non-empty assertions. Adds <1s to runtime.
SPOT_CHECKED=0
for c in "${CONDITIONS[@]}"; do
  for w in "${WEEKS[@]}"; do
    for t in "${TIMES[@]}"; do
      f="$DEST_BASE/$c/week_$w/$t/1.webp"
      [[ -s "$f" ]] || err "Spot-check failed: $f missing or zero-byte"
      SPOT_CHECKED=$((SPOT_CHECKED + 1))
    done
  done
done
[[ "$SPOT_CHECKED" -eq 144 ]] || err "Spot-check loop ran $SPOT_CHECKED iterations, expected 144"
log "  144 per-slot non-empty file spot-checks ✓"

#------------------------------------------------------------
# Phase 5 — regenerate OG static cards
#------------------------------------------------------------

log "Phase 5: regenerate og/*.jpg from new WebP sources"
node tools/build-og-images.mjs
OG_COUNT=$(num "$(find og -maxdepth 1 -name '*.jpg' -type f | wc -l)")
[[ "$OG_COUNT" -eq 12 ]] || err "Expected 12 og/*.jpg files (9 conditions + default + 2 aliases), got $OG_COUNT"
[[ -s "og/cold-clear.jpg" ]] || err "og/cold-clear.jpg missing or empty"
log "  og/ regenerated: 12 files, cold-clear.jpg present ✓"

#------------------------------------------------------------
# Phase 6 — post-promote vitest
#------------------------------------------------------------

log "Phase 6: post-promote vitest"
if ! TEST_OUT=$(npx vitest run 2>&1); then
  err "Post-promote vitest FAILED — review before committing. Last lines:
$(echo "$TEST_OUT" | tail -10)"
fi
POST_PASS=$(num "$(echo "$TEST_OUT" | grep -oE "Tests +[0-9]+ passed" | grep -oE "[0-9]+" | head -1 || true)")
[[ -n "$POST_PASS" && "$POST_PASS" -ge "$BASELINE_PASS" ]] || err "Test regression: '$POST_PASS' < '$BASELINE_PASS'"
log "  vitest: $POST_PASS tests pass ✓ (baseline was $BASELINE_PASS)"

#------------------------------------------------------------
# Phase 7 — scoped stage (explicit paths only, no `git add -A`)
#------------------------------------------------------------

log "Phase 7: scoped git add (explicit paths only)"

# Explicit-path stage. NEVER -A. The `--` guards against any weirdness with
# argument parsing if path names start with -.
# Bundle: asset migration + binary-rule .gitattributes + OG WebP→JPEG fix +
# the plan/review/report/script so the commit's history-of-record contains
# its own full justification.
git add -- \
  assets/images/bg/ \
  og/ \
  .gitattributes \
  api/og.js \
  assets/weather-visuals.js \
  tests/og-paths.test.js \
  docs/promote-plan-2026-05-24.md \
  docs/promote-review-2026-05-24.md \
  docs/promote-report-2026-05-24.md \
  docs/promote-commit-message.txt \
  docs/og-fix-review-2026-05-24.md \
  scripts/promote-image-library.sh

# Report
log "  --- staged diff stat ---"
git diff --cached --stat | tail -20 >&2
log "  --- end staged diff stat ---"

STAGED_COUNT=$(num "$(git diff --cached --name-only | wc -l)")
log "  $STAGED_COUNT files staged"

log ""
log "PROMOTE PHASE COMPLETE — review then commit and push manually:"
log "    git commit -F docs/promote-commit-message.txt"
log "    git push origin main"
log ""
log "After push, verify Vercel deploy status and run live smoke tests"
log "(see docs/promote-plan-2026-05-24.md §9)."
